// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_vgkC2qxQi9yOX-0APPe-fosBLen60o',
    appId: '1:473809215:web:ffa178e7a1a43117dad38a',
    messagingSenderId: '473809215',
    projectId: 'backend-1b0c5',
    authDomain: 'backend-1b0c5.firebaseapp.com',
    storageBucket: 'backend-1b0c5.appspot.com',
    measurementId: 'G-D4PYE9KCBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1dviITb3S6hK2S--a0wme_wzDM0Rl4xE',
    appId: '1:473809215:android:3a57a1a8f15a307cdad38a',
    messagingSenderId: '473809215',
    projectId: 'backend-1b0c5',
    storageBucket: 'backend-1b0c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTioJCbL0KiQSYjz5OrCu_JUVn6Gkdqfg',
    appId: '1:473809215:ios:d59d992041d32ce6dad38a',
    messagingSenderId: '473809215',
    projectId: 'backend-1b0c5',
    storageBucket: 'backend-1b0c5.appspot.com',
    iosBundleId: 'com.example.fapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTioJCbL0KiQSYjz5OrCu_JUVn6Gkdqfg',
    appId: '1:473809215:ios:d59d992041d32ce6dad38a',
    messagingSenderId: '473809215',
    projectId: 'backend-1b0c5',
    storageBucket: 'backend-1b0c5.appspot.com',
    iosBundleId: 'com.example.fapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu_vgkC2qxQi9yOX-0APPe-fosBLen60o',
    appId: '1:473809215:web:f9e6cec6405b8101dad38a',
    messagingSenderId: '473809215',
    projectId: 'backend-1b0c5',
    authDomain: 'backend-1b0c5.firebaseapp.com',
    storageBucket: 'backend-1b0c5.appspot.com',
    measurementId: 'G-VR3ET26QFJ',
  );
}
